### ISSUE TITLE
Strange mod conflict with Armory

### ISSUE THREAD

**Issue by MeisterGeekz** [squeek502/AppleSkin#10]
Hi. I've got a very strange issue between AppleSkin and Armory mod and I'm not sure which of you to push the issue to. 

With AppleSkin installed NEI shows hardly any items and no recipes for the items added by armory.
[Image](http://imgur.com/XcQ8QsL)
With AppleSkin removed:
[Image](http://imgur.com/zV6xr1N)

With AppleSkin installed, if I click on any of the items, nothing happens. No recipes show at all

Versions:
AppleSkin - mc1.10.2-1.0.5
NEI - 1.10.2-2.1.3.220
[Armory](https://minecraft.curseforge.com/projects/armory-armoring-the-world) 1.10.2-1.2.0.0-416 (tried various versions of this and its dependency)

Many thanks

**Comment by squeek502** [comment]
Very strange indeed, and I'm not really sure how this sort of thing would be possible, as AppleSkin doesn't really do much except listen for Forge events and render some stuff.

Will see if I can reproduce this.

**Comment by squeek502** [comment]
So it seems like this is a weird issue related to load order, and doesn't seem to have anything specific to do with AppleSkin. I can reproduce the issue by doing the following:

- Remove AppleSkin
- Rename the JEI mod file to something like `ajei_1.10.2-3.14.7.419.jar` (so that it comes before `armory` alphabetically)

It seems like if *any* mod file comes before `armory` alphabetically, it somehow messes up the initialization of Armory and things like the JEI recipe handlers never get registered. Why that would be, I have no idea.

Closing as I don't think there's anything I can do about this, and it will probably need to be fixed on Armory's side. In the meantime, you can 'fix' it by renaming your AppleSkin mod file to something like `zAppleSkin-mc1.10.2-1.0.5.jar`.
