### ISSUE TITLE
Disabling Saturation overlay, still shows up.

### ISSUE THREAD

**Issue by TDarkShadow** [squeek502/AppleSkin#11]
Minecraft version; 1.11.2
Mod version; AppleSkin-mc1.11-1.0.6.jar

Even when 'show.saturation.hud.overlay' is disabled, if 'show.food.values.hud.overlay' is enabled, the saturation that gets restored still shows up.

Tested several times, including latest Forge (13.20.0.2309) and only Appleskin (1.0.6) installed.

**Comment by squeek502** [comment]
I think this is currently intended behavior.

Did you expect the combo of `show.saturation.hud.overlay=false` and `show.food.values.hud.overlay=true` to make it so that when holding food, only the hunger restored flashes and not the saturation? I hadn't thought of that, although it does make some sense.

**Comment by TDarkShadow** [comment]
I did, since it is also mentioned in the tooltip;
"If true, shows the hunger (and saturation if " + SHOW_SATURATION_OVERLAY_NAME + " is true) that would be restored by food you are currently holding"

**Comment by squeek502** [comment]
Ah, good point, I forgot I had done that. Will fix.
