### ISSUE TITLE
Suggestion: Replace Saturation overlay with sparkles

### ISSUE THREAD

**Issue by elamea** [squeek502/AppleSkin#130]
Hi there! I want to start out by saying this is a great mod and thank you for making it!

I use a resourcepack that changes up my hotbar, and the shape of my hunger bar is cake slices rather than drumsticks. As a result, the saturation overlay (an outline of the drumstick) looks odd over my cake slices. (see screenshot)

Recently, I had an idea that would make this mod compatible with custom hunger bar shapes. Instead of an outline of a drumstick, what if the saturation overlay was some golden pixel sparkles? This would remove the need to change the shape for any custom resourcepacks. 

You are under no obligation to take my suggestion. I can just change the saturation overlay to sparkles on my own personal copy of AppleSkin (I already made an edited icons.png which I attached, you're welcome to use it). This was just an idea I had for a small change that would make this mod more compatible with resourcepacks. 

![2021-07-23_11 23 52](https://user-images.githubusercontent.com/87742576/126812474-b097800d-6d1f-45f2-ba8f-b0bc61b8d3c5.png)
![icons](https://user-images.githubusercontent.com/87742576/126812322-5fe61e3e-14fe-4b60-8f46-53c3d84e8f31.png)

**Comment by squeek502** [comment]
I like the concept but I'm not sure there's a way of doing this that'd look decent without a lot of effort. The sparkles make the icons less clear and make it really tough to make out the difference between full and half saturation icons.

Ultimately I think it's okay that resource packs will need to have their own AppleSkin icon texture in order to be consistent.
