### ISSUE TITLE
Appleskin attempts to render insanely large amounts of hunger points in tooltip

### ISSUE THREAD

**Issue by DrDoom347** [squeek502/AppleSkin#15]
I have found an issue when using this mod with my own mod, [https://minecraft.curseforge.com/projects/compressed-cookies](url). My mod adds food items with very large hunger values, and when you mouse over one of them with Appleskin installed, Appleskin attempts to render all of the hunger points in the tooltip, which freezes the game for extended amounts of time. It would be helpful if Appleskin had a limit on the amount of hunger points that it attempted to render in the tooltip, which would make using it with mods that add very large amounts of hunger on items MUCH more user friendly.

**Comment by squeek502** [comment]
Funnily enough, I have a system in place to handle this issue for huge saturation (drawing something like `100x <icon>` instead of 100 icons; see https://github.com/joshiejack/Mariculture/issues/125 for why it was implemented), but I never thought to apply it to hunger.

Should be an easy fix, will try to get to it soon.

**Comment by DrDoom347** [comment]
Awesome, thanks for the speedy response. Glad you have a good way to change it. A few things out of curiosity... Could there be a config to have a blacklist/whitelist of items that show their food values? Might be somewhat useful in modpack creation if the author wanted to hide the values of some foods but allow the player to see others. Also, does Appleskin not display extra saturation points past 20? I noticed that my food items weren't showing more than that, even though they theoretically should.

**Comment by squeek502** [comment]
Re-opening; will close it once the fix is implemented.

> Also, does Appleskin not display extra saturation points past 20?

Yes. This is because a player's saturation can never go above their current hunger, so any saturation above 20 is technically irrelevant for players (though obviously not for things like culinary generators). Will change that and/or create a config option for it ([link to the relevant code to remind myself](https://github.com/squeek502/AppleSkin/blob/1.10.2/java/squeek/appleskin/helpers/FoodHelper.java#L23)).

> Could there be a config to have a blacklist/whitelist of items that show their food values? Might be somewhat useful in modpack creation if the author wanted to hide the values of some foods but allow the player to see others.

Created a new issue for this: #16

**Comment by squeek502** [comment]
Should be fixed in v1.0.8:
- https://minecraft.curseforge.com/projects/appleskin/files
- https://github.com/squeek502/AppleSkin/releases/tag/v1.0.8
