### ISSUE TITLE
[1.12] Conflict with mod Charcoal Pit

### ISSUE THREAD

**Issue by OneEyeMaker** [squeek502/AppleSkin#18]
Hello.
Found very strange conflict between AppleSkin and Charcoal Pit (https://minecraft.curseforge.com/projects/charcoal-pit).
With AppleSkin all blocks of this mod look like ones haven't blockstate/model, texture and localization:
https://imgur.com/a/2UJHm

I tested and can confirm this issue with only JEI, Charcoal Pit and AppleSkin. (Without JEI I *can't* confirm it).
I can't say, on which side problem occurs (AppleSkin/Charcoal Pit or JEI).

Please, fix this issue. Say me, if I should report it to contributors of JEI.

MC 1.12.2
Forge build 2537-2541
AppleSkin 1.0.9
Charcoal Pit 1.7
JEI 4.8.0.114

**Comment by squeek502** [comment]
Reminds me of https://github.com/squeek502/AppleSkin/issues/10, which is still confusing to me. Try renaming your AppleSkin jar to something like `zAppleSkin-mc1.12-1.0.9.jar` to see if that fixes it.

**Comment by OneEyeMaker** [comment]
@squeek502 
Yep. Renaming mod file works for me. Thank you.

If I understand correctly, to work perfectly, your mod should be loaded last.
On 1.7.10 for this purpose GregTech did some *hacks*. Maybe, some of these are relevant for 1.12:
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/GT_Mod.java#L517-L542

**Comment by squeek502** [comment]
It's unlikely that it has anything to do with AppleSkin, since AppleSkin really doesn't do much of anything that could interfere (it just listens for some Forge events). Rather, Charcoal Pit probably needs to be loaded *first*, and any other mod that comes first alphabetically would cause the same problem (you can test this by removing AppleSkin, and renaming JEI to something like `ajei_1.12-4.8.0.114.jar`).

Why the load order messes things up for Charcoal Pit I don't really know.

**Comment by OneEyeMaker** [comment]
Ok. Thank you anyway.
