### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'appleskin'! Exit Code: -1

### ISSUE THREAD

**Issue by FallenOfficer** [squeek502/AppleSkin#186]
Running 1.18.2, has fabric API installed, and is fabric version of the download. Can't launch to main screen. Didn't see any other issues that have been resolved.
Crashlog:
[crash-2022-05-14_19.50.42-client.txt](https://github.com/squeek502/AppleSkin/files/8694218/crash-2022-05-14_19.50.42-client.txt)

**Comment by FallenOfficer** [comment]
Removing a mod, REI(Roughly Enough Items), resolves this issue.

REI is the fabric version of the Forge JEI(Just Enough Items)

**Comment by squeek502** [comment]
Thanks for reporting this.

My guess is that we need to update our version of Cloth Config.

**Comment by squeek502** [comment]
Turns out this is a false positive crash. REI 7.4.456 is only for Minecraft 1.18.1, not 1.18.2, and for whatever reason that's causing the crash you're experiencing.

If you download the latest REI version for MC 1.18.2 here it should work fine:

https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/3768212
