### ISSUE TITLE
Crashes with specific config in Spice of Fabric

### ISSUE THREAD

**Issue by C-Higgins** [squeek502/AppleSkin#247]
I'm unsure if this is a bug in AppleSkin or Spice of Fabric; both are mentioned in the logs below. This bug occurs when setting the Spice of Fabric config in this way:
```
	food: {
		// Expression that determines the food level to restore when eating a food item
		// default: hungerValue * power(0.7, timesEaten)
		// 	Must be a valid expression
		hunger: max((hungerValue * power(0.7, timesEaten)), 1)
	}
```

If that is the config, then hovering over a food item causes a client-side crash: https://paste.ee/p/IcBkL

M: https://github.com/Siphalor/spiceoffabric/issues/96

**Comment by squeek502** [comment]
Looks similar to the crash that was fixed in https://github.com/squeek502/AppleSkin/pull/235

**Comment by C-Higgins** [comment]
I forgot to add the version. This is with AppleSkin` 2.4.1+mc1.19` and SoF `1.6.0-beta.4+1.19.2` on MC 1.19.2

**Comment by C-Higgins** [comment]
If this was fixed in 2.4.4, could you backport the fix to 1.19.2? 2.4.4 is listed as 1.19.4 only.

**Comment by SAGESSE-CN** [comment]
Siphalor/capsaicin issue, resolved in

https://github.com/Siphalor/capsaicin/commit/19c8958f521f4a3338b355aed826863b81207d1e#diff-97caeb4c263640c25fcdf7dedbf0360439340fa249e203338166491c02f6c803L152


the 2.4.4 not crash, because we enchanted the food item check. this issue not fixed, try update or contact siphalor.

**Comment by C-Higgins** [comment]
Appears to be fixed in latest versions
