### ISSUE TITLE
Saturation value as NaN

### ISSUE THREAD

**Issue by DrTeletubbie** [squeek502/AppleSkin#254]
saturation value in f3 shows as NaN, and in the HUD the yellow is gone, as if no longer working
![2023-07-20_17 52 14](https://github.com/squeek502/AppleSkin/assets/78572209/c5dc55e8-8a0b-4865-bc88-cc2f0c0791f7)
![2023-07-20_17 58 37](https://github.com/squeek502/AppleSkin/assets/78572209/55bd65b6-940b-472b-ba72-e42914428366)

**Comment by DrTeletubbie** [comment]
Holding both vanilla food items and modded food items also does not show the saturation bar

**Comment by squeek502** [comment]
My guess is that this is caused by some other mod and you actually currently have `NaN` saturation (e.g. you ate some food with a `NaN` saturation modifier or something like that).

I believe the only way this could be caused by AppleSkin itself would be that the syncing of the saturation from server to client is faulty, but that seems pretty unlikely since this is the first of this type of report AppleSkin has ever gotten.

**Comment by DrTeletubbie** [comment]
I'll check mod compatibility if something seems off, though everything went fine with the mods present

**Comment by DrTeletubbie** [comment]
Created a new world, it now works, definetly a mod compat issue, you can close the thread if you want
edit: although editing the player data from the world folder with an NBTExplorer did not work, the DAT file just duplicates itself

**Comment by DrTeletubbie** [comment]
Though, is there a way to reset world data of a certain mod?

**Comment by DrTeletubbie** [comment]
Alright, quick update: NBTExplorer on player data should fix it

**Comment by DrTeletubbie** [comment]
didnt work

**Comment by DrTeletubbie** [comment]
OMMOGGGGG IT WORKED
nbt editing did the job
though the cause of the bug is unknown
