### ISSUE TITLE
[Feature] 1.20.3/4 Support

### ISSUE THREAD

**Issue by R00tB33rMan** [squeek502/AppleSkin#279]
Hate to be the one to shoot this message; however, the mod crashes when used on 1.20.3/4. Hope all is well and I can't wait to hopefully see a 1.20.3-4 iteration. Thank you for your hard work!

**Comment by squeek502** [comment]
The code changes have been made:
- https://github.com/squeek502/AppleSkin/commit/88afc1bba810671eb4b36518dea888e1665d31b6
- https://github.com/squeek502/AppleSkin/commit/7f6560a0afdc7fd25420aa81cce85e0aa294633a

but right now I'm waiting on cloth-config to be updated before releasing a new version since the Fabric version depends on it.

**Comment by zChenX1** [comment]
> The code changes have been made:
> 
> * [88afc1b](https://github.com/squeek502/AppleSkin/commit/88afc1bba810671eb4b36518dea888e1665d31b6)
> * [7f6560a](https://github.com/squeek502/AppleSkin/commit/7f6560a0afdc7fd25420aa81cce85e0aa294633a)
> 
> but right now I'm waiting on cloth-config to be updated before releasing a new version since the Fabric version depends on it.

cloth-config has been updated to 1.20.3~1.20.4 version.

**Comment by R00tB33rMan** [comment]
Awesome! Used the branch the second I saw it, since I assumed for some weird reason that it was in 1.20.1-fabric. Mod appears to work fine, even with the latest Cloth Config changes!

**Comment by squeek502** [comment]
Released a new version for Fabric. The Neoforge version for 1.20.2 works fine for 1.20.3/1.20.4 so no update required there.
