### ISSUE TITLE
Hardcore heart icons don't work when Colorful Hearts is installed

### ISSUE THREAD

**Issue by RoyalReject** [squeek502/AppleSkin#291]
While in hardcore change the visualization of potential heath restored to match hardcore hearts
![2024-03-17_20 57 49](https://github.com/squeek502/AppleSkin/assets/32550284/28c1ff2a-1d97-40eb-ae3f-62b12731de71)

**Comment by squeek502** [comment]
What version of AppleSkin/what version of Minecraft are you using? This functionality already exists in the code:

https://github.com/squeek502/AppleSkin/blob/10130b35f84ea0a3af2193a30e6c40f8e0799002/java/squeek/appleskin/client/HUDOverlayHandler.java#L290

but it may have regressed/not be working in certain versions.

**Comment by RoyalReject** [comment]
I just noticed that as I was looking through the source to create a PR.
Minecraft: 1.20.4
NeoForge: 20.4.200
AppleSkin: 1.20.4-2.5.1

**Comment by squeek502** [comment]
Sounds like one of two things is going wrong:

https://github.com/squeek502/AppleSkin/blob/8b3fad1ddde91b8319a78659b2d7b0df12bcfb76/java/squeek/appleskin/client/HUDOverlayHandler.java#L327

ends up with the value `false` instead of `true`

or

https://github.com/squeek502/AppleSkin/blob/8b3fad1ddde91b8319a78659b2d7b0df12bcfb76/java/squeek/appleskin/helpers/TextureHelper.java#L50-L58

is returning the wrong texture

**Comment by RoyalReject** [comment]
Still looking at it but it seems to be returning true.
![image](https://github.com/squeek502/AppleSkin/assets/32550284/46a9f7a1-4442-457f-94ea-8c9dc7bcc437)

**Comment by RoyalReject** [comment]
Actually its working in the dev environment, It might be a conflict with another mod
![2024-03-17_21 19 06](https://github.com/squeek502/AppleSkin/assets/32550284/3ae0ed61-3aee-434b-8ff1-c34422d83370)

**Comment by RoyalReject** [comment]
Okay confirmed it conflicts with https://www.curseforge.com/minecraft/mc-mods/colorful-hearts

**Comment by squeek502** [comment]
Looks like they [disable AppleSkin's health HUD rendering](https://github.com/Terrails/colorful-hearts/blob/79c2cd2474e7389aa03eeeef9b0a18b676d0e984/neoforge/src/main/java/terrails/colorfulhearts/neoforge/compat/AppleSkinForgeCompat.java#L33) and fully reimplement it:

https://github.com/Terrails/colorful-hearts/blob/79c2cd2474e7389aa03eeeef9b0a18b676d0e984/common/src/main/java/terrails/colorfulhearts/compat/AppleSkinCompat.java#L20

Closing this since the fix would need to be implemented in Colorful Hearts.
