### ISSUE TITLE
Food properties in 1.21

### ISSUE THREAD

**Issue by SiverDX** [squeek502/AppleSkin#316]
https://github.com/squeek502/AppleSkin/blob/4975a9f0b1b10ecd14eece8901e028e52238fd40/java/squeek/appleskin/helpers/FoodHelper.java#L55

posts the `FoodValuesEvent`

https://github.com/squeek502/AppleSkin/blob/4975a9f0b1b10ecd14eece8901e028e52238fd40/java/squeek/appleskin/client/TooltipOverlayHandler.java#L278

calls `FoodHelper#query` and afterwards posts the event again with the modified values from said event (meaning the modification happens twice)

`defaultFood` is also not final, meaning other mods could modify it

for neoforge I also recommend using `getFoodProperties` instead

**Comment by squeek502** [comment]
The double event is a bug.

---

`defaultFood` being non-final is intentional, since the use-case this was originally designed for was [Hunger Overhaul](https://www.curseforge.com/minecraft/mc-mods/hunger-overhaul) + [The Spice of Life](https://www.curseforge.com/minecraft/mc-mods/the-spice-of-life) working together, so:
- Hunger Overhaul changed the default and modified values for every food
- The Spice of Life changed the modified food values (depending on how often that food has been eaten by that player), but left the default alone

AppleSkin can then render the tooltip like this (this is from an old AppleSkin version):

![](https://i.imgur.com/X9d4BHV.png)

---

`getFoodProperties` does seem like the better thing to use

**Comment by squeek502** [comment]
Addressed in v3.0.5, thanks for the report!
