### ISSUE TITLE
Crash on server bootup

### ISSUE THREAD

**Issue by ImAK9** [squeek502/AppleSkin#34]
Fabric Loader: 0.4.4 Build 138
Yarn: 1.14 Build 3
AppleSkin: 1.0.4

Crashlog: https://pastebin.com/Jq7pcChs

**Comment by squeek502** [comment]
Might be a Fabric Loader problem? Looks like this is what @raphydaphy was trying to fix in these commits:
- https://github.com/raphydaphy/AppleSkin/commit/799e65a1951c68f4a84dc45a69315e964039ca1e
- https://github.com/raphydaphy/AppleSkin/commit/67815b30f1b82e90abf3aed8e90a1695bd5620ba

but according to the commit message: "tried to update but ultimately failed because loader br0k3e" and "lol it still doesn't work".

Do other mods work with that loader version?

**Comment by ImAK9** [comment]
Everything works fine except Apple Skin and Epicurean Gastronomy. Raphy used the 0.4.2+build.132 loader tho.. Not sure if fixed after that.

**Comment by squeek502** [comment]
Ok, will take a better look, thanks for reporting it.

**Comment by ImAK9** [comment]
Alright, no problem!

**Comment by ImAK9** [comment]
@squeek502 Any ideas on what it could be?

**Comment by squeek502** [comment]
I think AppleSkin was just compiled against a version that's too old at this point. Updating the build environment to use all the latest stuff should fix it, almost done with that.

**Comment by ImAK9** [comment]
Aight, thanks!

**Comment by squeek502** [comment]
Should be fixed in v1.0.5: https://minecraft.curseforge.com/projects/appleskin/files/2704117
