### ISSUE TITLE
[1.16.2] Missing food tooltips on ItemStacks in inventory?

### ISSUE THREAD

**Issue by SnowShock35** [squeek502/AppleSkin#77]
It appears that in the latest 1.16.2 build of apple skin the tooltips for item stacks that are food items don't appear whether you're holding shift or not holding shift. Has it yet to be implemented or is this a bug? If it is the latter I will update this post with more information.

**Comment by squeek502** [comment]
Sounds like a bug.

**Comment by squeek502** [comment]
This is a Forge bug. Forge released before fully updating everything. All the RenderTooltipEvent stuff is commented out:

https://github.com/MinecraftForge/MinecraftForge/blob/132cc3659d34826634650c34b9eba165fcccb591/src/main/java/net/minecraftforge/fml/client/gui/GuiUtils.java#L244-L427

Will leave this open until it gets fixed in Forge.

**Comment by SnowShock35** [comment]
Brilliant thanks for letting me know Squeek 👍

**Comment by Glease** [comment]
[Forge has (claimed to) fixed the issue upstream](https://github.com/MinecraftForge/MinecraftForge/commit/873c4904701f3213d9b50973504a72c846f33d98#diff-27e61e29e205f4824c4815e494dcff34), but it is only in the 1.16.3 branch. Any plan to update?

**Comment by squeek502** [comment]
Update: https://github.com/MinecraftForge/MinecraftForge/pull/7268 was merged which is half of the required fix, but the other half is still unimplemented. The RenderTooltipEvent is still not being fired because [things are still not hooked up in Screen and other places that tooltips are rendered](https://github.com/MinecraftForge/MinecraftForge/blob/ac19d1bf2b21f7642b1c58cc26e61f7b99c5041e/patches/minecraft/net/minecraft/client/gui/screen/Screen.java.patch#L22).

Note that once it's fixed in Forge, it won't require an update of AppleSkin, since AppleSkin is already listening for the event; Forge is just not firing the RenderTooltipEvent.

cc @Glease who I think deleted a comment asking about this

**Comment by Glease** [comment]
Yeah I was on the impression that no update to apple skin is required, so I deleted the comment.

**Comment by squeek502** [comment]
Should be fixed as of https://github.com/MinecraftForge/MinecraftForge/pull/7378 / `1.16.3-34.1.11`.
