### ISSUE TITLE
[compatability] not displayed in Roughly Enough Items

### ISSUE THREAD

**Issue by milkev** [squeek502/AppleSkin#89]
when using REI, the food values are not shown, and are only shown once in your inventory.

using the latest fabric version of REI and appleskin.

**Comment by squeek502** [comment]
From taking a quick look at the REI source, it looks like it only ever calls the `matrices, lines, mouseX, mouseY` overload of `renderTooltip`, whereas AppleSkin needs the one with `ItemStack` to be called in order to [cache the ItemStack for context when rendering the tooltip](https://github.com/squeek502/AppleSkin/blob/9239c5789c613ce28daea156974a4ca148b714a1/java/squeek/appleskin/mixin/GuiMixin.java#L20-L30)

So, will need some other way to get the ItemStack that is being hovered in the REI screen for use in `renderTooltip`.

EDIT: Possibly [FocusedStackProvider](https://github.com/shedaniel/RoughlyEnoughItems/blob/5.x/RoughlyEnoughItems-api/src/main/java/me/shedaniel/rei/api/FocusedStackProvider.java) ? Or maybe just some code [like this](https://github.com/shedaniel/RoughlyEnoughItems/blob/277b7f97681548c7e919f45791b0a613506a16d7/RoughlyEnoughItems-runtime/src/main/java/me/shedaniel/rei/impl/RecipeHelperImpl.java#L433-L437)

**Comment by SAGESSE-CN** [comment]
@squeek502 I tried ported to REI, but FocuseStackProvider does not seem to customize of the rendering.

**Comment by squeek502** [comment]
Does #98 not fix this?

**Comment by SAGESSE-CN** [comment]
> Does #98 not fix this?

not fix it, REI will fetch base tooltip from `ItemStack.getTooltip`,  and the rendering with custom render api.

**Comment by squeek502** [comment]
Looked into this a bit and found something that should work but the rendering is still broken for some reason:

https://github.com/squeek502/AppleSkin/tree/1.16-fabric-rei (https://github.com/squeek502/AppleSkin/commit/32206f0b8379684398d79fd3aee258b79fbb76e5)

> Moving the tooltip mixin from Screen.getTooltipFromItem (which just calls ItemStack.getTooltip internally) to ItemStack.getTooltip itself makes it so AppleSkin can add its tooltips to the list in REI, since REI calls ItemStack.getTooltip directly. However, for some reason, the icons don't render, even though when stepping through the code, all the AppleSkin rendering code gets called and the x & y coordinates seem to make sense. Not sure why that is happening.

**Comment by SAGESSE-CN** [comment]
Before REI 5.9.0 using [custom render](https://github.com/shedaniel/RoughlyEnoughItems/blob/33de3995b677f72267158baa60e2d54b09bc4d14/RoughlyEnoughItems-runtime/src/main/java/me/shedaniel/rei/gui/ContainerScreenOverlay.java#L92)
After REF 5.9.0 using [screen.renderTooltip](https://github.com/shedaniel/RoughlyEnoughItems/commit/e5e80c88ae7f1bd512307be67d6631f9f2abbc1b)

You can try REF a version after 5.9.0

**Comment by squeek502** [comment]
I was testing with REI `5.12.248` using:

```
modImplementation "me.shedaniel:RoughlyEnoughItems:5.12.248"
```

**Comment by sagesse-cn** [comment]
![image](https://user-images.githubusercontent.com/6903353/120885954-23fc7c00-c61e-11eb-8419-0817eb4230f8.png)
It looks like the render method is working, just the texture can't render

**Comment by SAGESSE-CN** [comment]
![image](https://user-images.githubusercontent.com/6903353/120886174-375c1700-c61f-11eb-8e96-d66667a1235f.png)

well, that's because zlevel is to large

**Comment by SAGESSE-CN** [comment]
```
diff --git a/java/squeek/appleskin/client/TooltipOverlayHandler.java b/java/squeek/appleskin/client/TooltipOverlayHandler.java
index 74897c3..ce5f35b 100644
--- a/java/squeek/appleskin/client/TooltipOverlayHandler.java
+++ b/java/squeek/appleskin/client/TooltipOverlayHandler.java
@@ -287,9 +287,6 @@ public class TooltipOverlayHandler
                RenderSystem.enableBlend();
                RenderSystem.defaultBlendFunc();
 
-               matrixStack.push();
-               matrixStack.translate(0.0D, 0.0D, 500D); // zLevel must higher than of the background.
-
                // Render from right to left so that the icons 'face' the right way
                x += (foodOverlay.hungerBars - 1) * 9;
 
@@ -368,8 +365,6 @@ public class TooltipOverlayHandler
                        matrixStack.pop();
                }
 
-               matrixStack.pop();
-
                RenderSystem.disableBlend();
                RenderSystem.color4f(1.0F, 1.0F, 1.0F, 1.0F);
```

**Comment by squeek502** [comment]
Nice, thanks for finding the fix @sagesse-cn!

Should be fixed as of https://github.com/squeek502/AppleSkin/commit/b2ed069e1f35c52b8f33dd341ef3c591ee773bfc
